const mongoose = require('mongoose');

const EmailSchema = mongoose.Schema({
    // The actual email address.
    value: String,

    // The type of email address (home, work, etc.).
    type: String
});

const PhotoSchema = mongoose.Schema({
    // The URL of the image.
    value: String
});

module.exports = mongoose.Schema({

    // The provider with which the user authenticated (facebook, twitter, etc.).
    profile: String,

    // A unique identifier for the user, as generated by the service provider.
    id: String,

    // The name of this user, suitable for display.
    displayName: String,

    // The token returned from the provider
    token: String,

    name: {
        // The family name of this user, or "last name" in most Western languages.
        familyName: String,

        // The given name of this user, or "first name" in most Western languages.
        givenName: String,

        // The middle name of this user.
        middleName: String
    },

    emails: [EmailSchema],
    photos: [PhotoSchema]
});